### ISSUE TITLE
networkx comparability issue

### ISSUE THREAD

**Issue by XinweiFu** [ririhedou/dr_droid#4]
Hi,

I have this problem on running the code:

/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2699: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
Namespace(apkinfo=True, feainfo=True, mlparameters=False, predict='apks/Geinimi--2e998614b17adbafeb55b5fb9820f63aec5ce8b4.apk', w=False)
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    runApkInfo(input_file)
  File "/home/fuxinwei/temp/dr_droid/AppInfo.py", line 26, in runApkInfo
    new_app = newStart(input_file)
  File "/home/fuxinwei/temp/dr_droid/NewApp.py", line 102, in __init__
    self.Tab_CallInOut()
  File "/home/fuxinwei/temp/dr_droid/NewApp.py", line 144, in Tab_CallInOut
    self._Callinout = YY_CallInOut(M,C,self.classlist) 
  File "/home/fuxinwei/temp/dr_droid/Callinout.py", line 22, in __init__
    self.process_class_graph(classInvokelist, KE_classlist)
  File "/home/fuxinwei/temp/dr_droid/Callinout.py", line 115, in process_class_graph
    self.fcgnx_class_level = nx.DiGraph(nx.from_pydot(dgraph_class))
AttributeError: 'module' object has no attribute 'from_pydot'

could you help me to look into the problem?

**Comment by ririhedou** [comment]
Could you check  your networkX version?

IndentationError: unexpected indent
>>> import pkg_resources
>>> pkg_resources.get_distribution("networkx").version

1.9 has this 
https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.drawing.nx_pydot.from_pydot.html
>>> K5=nx.complete_graph(5) 
>>> A=nx.to_pydot(K5) 
>>> G=nx.from_pydot(A) # return MultiGraph
>>> G=nx.Graph(nx.from_pydot(A)) # make a Graph instead of MultiGrap

But 1.11 has this:
http://networkx.readthedocs.io/en/stable/reference/generated/networkx.drawing.nx_pydot.from_pydot.html
>>> K5 = nx.complete_graph(5) 
>>> A = nx.nx_pydot.to_pydot(K5) 
>>> G = nx.nx_pydot.from_pydot(A) # return MultiGraph

I will fix this and update soon
Best,

**Comment by XinweiFu** [comment]
Hi,

@ririhedou  @lzto 
Thanks for your info,  after I install some other dependences: 
sudo pip install pydotplus

I can run the code then.

**Comment by ririhedou** [comment]
Cool, please let me know if you have any other problems :)
